included: # paths to include during linting. `--path` is ignored if present.
  - include_folders
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - excluded_folders
  
only_rules:
  - anyobject_protocol
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - computed_accessors_order
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - duplicate_enum_cases
  - duplicate_imports
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - fallthrough
  - file_length
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_random
  - line_length
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_function_chains
  - multiline_parameters
  - nesting
  - no_space_in_method_call
  - opening_brace
  - operator_usage_whitespace
  - orphaned_doc_comment
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - private_over_fileprivate
  - prohibited_super_call
  - protocol_property_accessors_order
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - single_test_class
  - sorted_first_last
  - statement_position
  - static_operator
  - strict_fileprivate
  - superfluous_disable_command
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - toggle_bool
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_capture_list
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - void_return
  - weak_delegate
  - yoda_condition
  
anyobject_protocol:
  severity: error

block_based_kvo:
  severity: error

class_delegate_protocol:
  severity: error
  
closure_body_length:
  warning: 20
  error: 20

contains_over_filter_count:
  severity: error

contains_over_filter_is_empty:
  severity: error

contains_over_first_not_nil:
  severity: error

contains_over_range_nil_comparison:
  severity: error

cyclomatic_complexity:
  warning: 10
  error: 10
  ignores_case_statements: true

discarded_notification_center_observer:
  severity: error

duplicate_enum_cases:
  severity: error

empty_collection_literal:
  severity: error

empty_count:
  severity: error

empty_enum_arguments:
  severity: error

empty_parameters:
  severity: error

empty_parentheses_with_trailing_closure:
  severity: error

empty_string:
  severity: error

explicit_init:
  severity: error

fallthrough:
  severity: error
  
file_length:
  warning: 400
  error: 400
  ignore_comment_only_lines: true

first_where:
  severity: error

for_where:
  severity: error
  
force_unwrapping:
  severity: error
  
function_body_length:
  warning: 40
  error: 40

generic_type_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 20
    error: 20
  excluded: []
  validates_start_with_lowercase: true

identical_operands:
  severity: error

identifier_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 50
    error: 50
  excluded: [id, i, up, ds, x, y]
  validates_start_with_lowercase: true

implicitly_unwrapped_optional:
  severity: error

is_disjoint:
  severity: error
  
joined_default_parameter:
  severity: error

large_tuple:
  warning: 4
  error: 4

last_where:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

legacy_hashing:
  severity: error

legacy_multiple:
  severity: error

legacy_random:
  severity: error

line_length:
  warning: 150
  error: 150
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true
  
overridden_super_call:
  severity: error

private_action:
  severity: error

private_outlet:
  severity: error
  
prohibited_super_call:
  severity: error
  
reduce_into:
  severity: error

superfluous_disable_command:
  severity: error

syntactic_sugar:
  severity: error

todo:
  severity: error

toggle_bool:
  severity: error

trailing_comma:
  severity: error

trailing_semicolon:
  severity: error
  
trailing_whitespace:
  ignores_empty_lines: true
  
type_body_length:
  warning: 400
  error: 400

type_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 50
    error: 50
  validates_start_with_lowercase: true

unneeded_break_in_switch:
  severity: error

unneeded_parentheses_in_closure_argument:
  severity: error

unowned_variable_capture:
  severity: error

unused_capture_list:
  severity: error

unused_declaration:
  severity: error

unused_enumerated:
  severity: error

unused_import:
  severity: error

unused_optional_binding:
  severity: error

void_return:
  severity: error

weak_delegate:
  severity: error

yoda_condition:
  severity: error
